title: AutoMeKin Documentation
theme: just-the-docs

url: https://emartineznunez.github.io

aux_links:
  Template Repository: https://github.com/emartineznunez/AutoMeKin


callouts:
  warning:
    title: Warning
    color: red
