title: AutoMeKin Documentation
description: Documentation for AutoMeKin
theme: just-the-docs

aux_links:
  AutoMeKin's Repository: https://github.com/emartineznunez/AutoMeKin

# External navigation links
nav_external_links:
  - title: Network visualization tools
    url: https://github.com/dgarayr/amk_tools
  - title: Try it on the Web
    url: https://rxnkin.usc.es/amk/
  - title: Open in Colab
    url: https://colab.research.google.com/github/emartineznunez/AutoMeKin/blob/main/AutoMeKin.ipynb
  - title: Get it from sylabs
    url: https://cloud.sylabs.io/library/emartineznunez/default/automekin
    
callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

logo: "/assets/images/Imagen1.png"
kramdown:
  input: GFM
  math_engine: mathjax # you can also set this field to 'katex'
